/** Coverwatch-matched industry routes and landing copy for PolicyWell. */

export type IndustryPage = {
  path: string;
  label: string;
  headline: string;
  support: string;
  title: string;
  hero?: string;
  categoryId: string;
  parentPath?: string;
};

export const INDUSTRY_PAGES: readonly IndustryPage[] = [
  {
    path: "/financial-products",
    label: "Financial Products",
    headline: "Life insurance and annuity products analyzed with policy-level clarity",
    support:
      "Compare term, whole life, indexed universal life, and annuity designs — funding, guarantees, riders, and illustration assumptions — with explainable recommendations.",
    title: "Financial Products | Life Insurance and Annuities",
    hero: "financial-products-hero",
    categoryId: "financial-products",
  },
  {
    path: "/life-insurance",
    label: "Life Insurance",
    headline: "Life insurance coverage built around the policy — not a generic package",
    support:
      "PolicyWell helps households and advisors compare term, whole life, and indexed universal life with explainable funding and coverage recommendations across carriers.",
    title: "Life Insurance Analysis and Intelligence",
    hero: "life-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/financial-products",
  },
  {
    path: "/life-insurance/term-insurance",
    label: "Term Life",
    headline: "Term life insurance with clear duration, conversion, and cash-back options",
    support:
      "Compare regular term and cash-back offer term side by side — death benefit design, conversion privileges, and rider fit — with human-reviewed recommendations.",
    title: "Term Life Insurance",
    hero: "term-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/life-insurance",
  },
  {
    path: "/life-insurance/cash-back-offer-term-insurance",
    label: "Cash Back Offer Term",
    headline: "Cash-back offer term life when the marketing pitch needs a second look",
    support:
      "Cash-back / return-of-premium style term can look attractive on a brochure. We unpack the real cost, lapse risk, and whether a regular term or permanent design fits better.",
    title: "Cash Back Offer Term Life Insurance",
    hero: "cash-back-offer-term-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/life-insurance/term-insurance",
  },
  {
    path: "/life-insurance/regular-term-insurance",
    label: "Regular Term",
    headline: "Regular term life insurance sized to the years you actually need coverage",
    support:
      "Level term designed around income replacement, mortgage years, and conversion options — without cash-back marketing complexity.",
    title: "Regular Term Life Insurance",
    hero: "regular-term-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/life-insurance/term-insurance",
  },
  {
    path: "/life-insurance/whole-life-insurance",
    label: "Whole Life",
    headline: "Whole life insurance with dividend and guaranteed-value clarity",
    support:
      "Permanent coverage, cash value, and dividend mechanics explained in plain language — so funding decisions are grounded in the contract, not the illustration alone.",
    title: "Whole Life Insurance",
    hero: "whole-life-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/life-insurance",
  },
  {
    path: "/life-insurance/indexed-universal-life-insurance",
    label: "Indexed Universal Life",
    headline: "Indexed universal life insurance when the index story needs underwriting discipline",
    support:
      "IUL illustrations can outrun reality. We stress-cap assumptions, cost of insurance, and funding floors so the policy design matches the household goal.",
    title: "Indexed Universal Life (IUL) Insurance",
    hero: "indexed-universal-life-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/life-insurance",
  },
  {
    path: "/annuities",
    label: "Annuities",
    headline: "Annuity coverage and product fit across accumulation and income designs",
    support:
      "Variable, fixed indexed, fixed, and immediate annuities — compared on fees, guarantees, surrender schedules, and income riders with advisor-ready explanations.",
    title: "Annuity Analysis and Intelligence",
    hero: "annuities-hero",
    categoryId: "financial-products",
    parentPath: "/financial-products",
  },
  {
    path: "/annuities/variable-annuity-insurance",
    label: "Variable Annuity",
    headline: "Variable annuity analysis when subaccounts and living benefits collide",
    support:
      "Separate-account risk, rider fees, and guaranteed living benefit tradeoffs — reviewed so accumulation and income claims stay tied to the contract.",
    title: "Variable Annuity",
    hero: "variable-annuity-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/annuities",
  },
  {
    path: "/annuities/fixed-indexed-annuity-insurance",
    label: "Fixed Indexed Annuity (FIA)",
    headline: "Fixed indexed annuity (FIA) clarity on caps, participation, and income riders",
    support:
      "Index-linked crediting is not market participation. We unpack caps, spreads, participation rates, and rider cost before the illustration becomes the plan.",
    title: "Fixed Indexed Annuity (FIA)",
    hero: "fixed-indexed-annuity-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/annuities",
  },
  {
    path: "/annuities/fixed-annuity-insurance",
    label: "Fixed Annuity",
    headline: "Fixed annuity and MYGA-style designs for rate certainty",
    support:
      "Multi-year guaranteed and traditional fixed annuities compared on declared rates, MVA, surrender windows, and liquidity needs.",
    title: "Fixed Annuity",
    hero: "fixed-annuity-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/annuities",
  },
  {
    path: "/annuities/immediate-annuity-insurance",
    label: "Immediate Annuity (SPIA)",
    headline: "Immediate annuity (SPIA) income when the paycheck needs to be contractual",
    support:
      "Single-premium immediate annuity structuring for lifetime or period-certain income — with clear treatment of refund features and survivor options.",
    title: "Immediate Annuity (SPIA)",
    hero: "immediate-annuity-insurance-hero",
    categoryId: "financial-products",
    parentPath: "/annuities",
  },
  {
    path: "/bar-insurance",
    label: "Bar",
    headline: "Bar insurance built for late-night venues",
    support: "Bar insurance for taverns, lounges, and nightclubs. Liquor liability, dram shop coverage, and assault & battery endorsements shopped across a variety of carriers.",
    title: "Bar Insurance & Liquor Liability",
    hero: "bar-insurance-hero",
    categoryId: "bar",
  },
  {
    path: "/catering-insurance",
    label: "Catering",
    headline: "Catering insurance built for off-premise events",
    support: "Catering insurance built for off-premise work: GL, hired & non-owned auto, equipment in transit, and event liquor liability. A variety of carriers, one broker.",
    title: "Catering Insurance for Event Caterers",
    hero: "catering-insurance-hero",
    categoryId: "catering",
  },
  {
    path: "/contractors",
    label: "Contractor",
    headline: "Contractor insurance that actually covers what you build",
    support: "Contractor insurance for GCs, subs, and specialty trades. We shop a variety of carriers for the right coverage at the best price. Free coverage review.",
    title: "Contractor Insurance",
    hero: "contractors-hero",
    categoryId: "contractor",
  },
  {
    path: "/contractors/electrician-insurance",
    label: "Electrician",
    headline: "Electrician insurance wired for the trade",
    support: "Electrician insurance for licensed commercial and residential crews. GL with completed operations, workers comp, commercial auto, and GC-ready endorsements.",
    title: "Electrician Insurance for Licensed Contractors",
    hero: "electrician-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/flooring-contractor-insurance",
    label: "Flooring Contractor",
    headline: "Flooring contractor insurance crafted for every install",
    support: "Flooring contractor insurance for hardwood, tile, LVP, and commercial TI crews. GL with completed ops, installation floater, pollution, and workers comp.",
    title: "Flooring Contractor Insurance for Installers",
    hero: "flooring-contractor-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/general-contractor-insurance",
    label: "General Contractor",
    headline: "General contractor insurance built for multi-trade builds",
    support: "General contractor insurance for multi-trade builds. GL with completed operations, NCCI 5606 workers comp, umbrella, builder's risk, and surety bonds.",
    title: "General Contractor Insurance",
    hero: "general-contractor-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/handyman-insurance",
    label: "Handyman",
    headline: "Handyman insurance scoped for the work you do",
    support: "Handyman insurance for solo operators and small crews. GL that meets Thumbtack and Angi requests, tools coverage, commercial auto, scope matched to your actual work.",
    title: "Handyman Insurance for Solo Operators",
    hero: "handyman-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/hvac-insurance",
    label: "HVAC",
    headline: "HVAC insurance tuned for mechanical contractors",
    support: "HVAC insurance for licensed mechanical contractors. GL with completed ops, NCCI 5537 workers comp, refrigerant pollution, rigger's liability, controls E&O.",
    title: "HVAC Insurance",
    hero: "hvac-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/landscaping-insurance",
    label: "Landscaping",
    headline: "Landscaping insurance designed for seasonal crews",
    support: "Landscaping insurance for maintenance, install, and seasonal crews. GL with pesticide endorsement, class 0042 workers comp, auto, and mobile equipment coverage.",
    title: "Landscaping Insurance",
    hero: "landscaping-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/painter-insurance",
    label: "Painter",
    headline: "Painter insurance tailored for residential and commercial crews",
    support: "Painter insurance for residential repaint and commercial crews. GL with completed ops, class 5474 workers comp, pollution endorsement for overspray, RRP coverage.",
    title: "Painter Insurance for Licensed Contractors",
    hero: "painter-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/plumber-insurance",
    label: "Plumber",
    headline: "Plumber insurance fitted for water damage risk",
    support: "Plumber insurance for licensed service and new-construction crews. GL with water damage endorsement, pollution for drain chemicals, workers comp, backflow E&O.",
    title: "Plumber Insurance for Licensed Contractors",
    hero: "plumber-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/contractors/roofing-insurance",
    label: "Roofing",
    headline: "Roofing insurance placed for high-risk contractors",
    support: "Roofing insurance placed through specialty and non-admitted markets. Hot-work endorsement, completed operations, and NCCI 5551 workers comp.",
    title: "Roofing Insurance",
    hero: "roofing-insurance-hero",
    categoryId: "contractor",
    parentPath: "/contractors",
  },
  {
    path: "/ecommerce",
    label: "Ecommerce",
    headline: "Ecommerce insurance built to scale with your brand",
    support: "Insurance decision support for ecommerce sellers and consumer brands. Product liability, recall coverage, and compliance for Amazon, Shopify, DTC, and CPG brands. a variety of carriers, a response within the next hour.",
    title: "Ecommerce & Consumer Brand Insurance",
    hero: "ecommerce-hero",
    categoryId: "ecommerce",
  },
  {
    path: "/ecommerce/alcoholic-beverage-insurance",
    label: "Alcoholic Beverage",
    headline: "Alcoholic beverage insurance built for DTC alcohol brands shipping across state lines",
    support: "Alcoholic beverage insurance for DTC brands selling wine, spirits, beer, and RTDs online. Liquor liability, product recall, multi-state compliance.",
    title: "Alcoholic Beverage Insurance for DTC Brands",
    hero: "alcoholic-beverage-insurance-hero",
    categoryId: "ecommerce",
    parentPath: "/ecommerce",
  },
  {
    path: "/ecommerce/beauty-and-cosmetics-insurance",
    label: "Beauty & Cosmetics",
    headline: "Beauty & cosmetics insurance formulated for product brands",
    support: "Beauty and cosmetics insurance for skincare, cosmetics, and personal care brands. Product liability, recall coverage, MoCRA compliance, and retail vendor COIs.",
    title: "Beauty & Cosmetics Insurance for Brands",
    hero: "beauty-and-cosmetics-insurance-hero",
    categoryId: "ecommerce",
    parentPath: "/ecommerce",
  },
  {
    path: "/ecommerce/clothing-store-insurance",
    label: "Clothing Store",
    headline: "Clothing store insurance tailored for online and retail sellers",
    support: "Clothing store insurance for online and retail apparel sellers. Product liability, commercial property, cyber coverage, and workers comp under NCCI 8008.",
    title: "Clothing Store Insurance",
    hero: "clothing-store-insurance-hero",
    categoryId: "ecommerce",
    parentPath: "/ecommerce",
  },
  {
    path: "/ecommerce/cpg-insurance",
    label: "CPG",
    headline: "Consumer packaged goods insurance built for retail and DTC brands",
    support: "Insurance for consumer packaged goods brands. Meet Target, Costco, and Amazon vendor requirements with product liability and recall coverage from a variety of carriers.",
    title: "Consumer Packaged Goods (CPG) Insurance",
    hero: "cpg-insurance-hero",
    categoryId: "ecommerce",
    parentPath: "/ecommerce",
  },
  {
    path: "/ecommerce/food-and-beverage-insurance",
    label: "Food & Beverage",
    headline: "Food & beverage insurance built for DTC and retail brands",
    support: "Food and beverage insurance for CPG brands selling through ecommerce and retail. Product liability, recall, and contamination coverage across a variety of carriers.",
    title: "Food & Beverage Insurance for Brands",
    hero: "food-and-beverage-insurance-hero",
    categoryId: "ecommerce",
    parentPath: "/ecommerce",
  },
  {
    path: "/ecommerce/pet-business-insurance",
    label: "Pet Business",
    headline: "Pet business insurance crafted for treats, food, and supplement brands",
    support: "Pet business insurance for food, treat, supplement, and toy brands. Product liability, recall coverage, and marketplace compliance for DTC and retail channels.",
    title: "Pet Business Insurance for Brands",
    hero: "pet-business-insurance-hero",
    categoryId: "ecommerce",
    parentPath: "/ecommerce",
  },
  {
    path: "/ecommerce/supplement-insurance",
    label: "Supplement",
    headline: "Supplement insurance designed for brands navigating FDA risk",
    support: "Supplement insurance for dietary supplement and nutraceutical brands. Product liability without ingredient exclusions, recall coverage, marketplace compliance.",
    title: "Supplement Insurance for Brands",
    hero: "supplement-insurance-hero",
    categoryId: "ecommerce",
    parentPath: "/ecommerce",
  },
  {
    path: "/garages",
    label: "Garage & Auto",
    headline: "Garage keepers insurance that protects your shop and your reputation",
    support: "Garage keepers insurance for repair shops, dealerships, and body shops. Garage liability, garagekeepers, dealer open lot from a variety of carriers. Free review.",
    title: "Garage Keepers Insurance & Auto Dealer Coverage",
    hero: "garage-auto-hero",
    categoryId: "garage-auto",
  },
  {
    path: "/garages/auto-dealer-insurance",
    label: "Auto Dealer",
    headline: "Auto dealer insurance built for new and used lots",
    support: "Auto dealer insurance for new, used, and independent dealerships. Dealer open lot, garage liability, surety bonds, and F&I E&O quoted across a variety of carriers.",
    title: "Auto Dealer Insurance",
    hero: "auto-dealer-insurance-hero",
    categoryId: "garage-auto",
    parentPath: "/garages",
  },
  {
    path: "/garages/auto-repair-insurance",
    label: "Auto Repair Shop",
    headline: "Auto repair shop insurance tuned for independent shops",
    support: "Auto repair shop insurance for mechanics and service centers. Garage liability, garagekeepers, workers comp, and pollution coverage quoted across a variety of carriers.",
    title: "Auto Repair Shop Insurance",
    hero: "auto-repair-insurance-hero",
    categoryId: "garage-auto",
    parentPath: "/garages",
  },
  {
    path: "/garages/body-shop-insurance",
    label: "Body Shop",
    headline: "Auto body shop insurance fitted for collision and paint shops",
    support: "Auto body and collision repair shop insurance. Garage liability, garagekeepers, spray booth and pollution coverage, and NCCI 8393 workers comp across a variety of carriers.",
    title: "Auto Body Shop & Collision Repair Insurance",
    hero: "body-shop-insurance-hero",
    categoryId: "garage-auto",
    parentPath: "/garages",
  },
  {
    path: "/garages/mechanic-insurance",
    label: "Mechanic",
    headline: "Mechanic insurance geared for mobile and self-employed mechanics",
    support: "Mechanics insurance for mobile, self-employed, and 1099 mechanics. General liability, tools coverage, commercial auto, and E&O quoted across a variety of carriers.",
    title: "Mechanic Insurance for Mobile & Self-Employed",
    hero: "mechanic-insurance-hero",
    categoryId: "garage-auto",
    parentPath: "/garages",
  },
  {
    path: "/garages/used-car-dealer-insurance",
    label: "Used Car Dealer",
    headline: "Used car dealer insurance sized for independent lots",
    support: "Used car dealer insurance for independent lots and BHPH operations. Garage liability, dealer open lot, surety bonds, and E&O quoted across a variety of carriers.",
    title: "Used Car Dealer Insurance",
    hero: "used-car-dealer-insurance-hero",
    categoryId: "garage-auto",
    parentPath: "/garages",
  },
  {
    path: "/grocery-stores",
    label: "Grocery Store",
    headline: "Grocery store insurance shopped across a variety of carriers",
    support: "Grocery store insurance across a variety of carriers, flat fee. Spoilage, equipment breakdown, liability, workers' comp, from one store to a multi-store program.",
    title: "Grocery Store Insurance: Quotes from a Variety of Carriers",
    hero: "grocery-stores-hero",
    categoryId: "grocery-store",
  },
  {
    path: "/grocery-stores/small-grocery-store-insurance",
    label: "Small Grocery Store",
    headline: "Small grocery store insurance shopped across a variety of carriers",
    support: "Small grocery store insurance for independent owner-operators: crime and cash coverage, single-cooler spoilage and breakdown, workers comp, and beer-wine.",
    title: "Small Grocery Store Insurance for Owners",
    hero: "small-grocery-store-insurance-hero",
    categoryId: "grocery-store",
    parentPath: "/grocery-stores",
  },
  {
    path: "/grocery-stores/supercenter-insurance",
    label: "Supercenter",
    headline: "Supercenter insurance shopped across a variety of carriers",
    support: "Supercenter insurance for big-box grocery and general-merchandise stores: products liability, garden center, auto-bay garagekeepers, and fuel-island UST.",
    title: "Supercenter Insurance: Food + General Store",
    hero: "supercenter-insurance-hero",
    categoryId: "grocery-store",
    parentPath: "/grocery-stores",
  },
  {
    path: "/grocery-stores/supermarket-insurance",
    label: "Supermarket",
    headline: "Supermarket insurance shopped across a variety of carriers",
    support: "Commercial insurance for supermarkets and large-format grocery stores: deli, bakery hood, pharmacy E&O, ammonia/CO2 refrigeration, spoilage, workers' comp.",
    title: "Supermarket Insurance for Grocery Businesses",
    hero: "supermarket-insurance-hero",
    categoryId: "grocery-store",
    parentPath: "/grocery-stores",
  },
  {
    path: "/homeowners-association-insurance",
    label: "Home Owner's Associations",
    headline: "Homeowners association insurance built around your community",
    support: "Homeowners association insurance for boards, self-managed HOAs, and management companies. Master policies, D&O, fidelity bonds, and liability for condos, townhomes, single-family, co-ops, and planned communities. Shop a variety of carriers.",
    title: "HOA Insurance",
    hero: "homeowners-association-insurance-hero",
    categoryId: "home-owners-associations",
  },
  {
    path: "/homeowners-association-insurance/community-association-management-insurance",
    label: "Community Association Management",
    headline: "Community Association Management Insurance for Your Portfolio",
    support: "Community association management insurance: manager E&O, crime and fidelity across client funds, cyber, and D&O. Scaled to your portfolio across a variety of carriers.",
    title: "Community Association Management Insurance",
    hero: "community-association-management-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/homeowners-association-insurance/condominium-association-insurance",
    label: "Condominium Association",
    headline: "Condominium Association Insurance Built Around Your Community",
    support: "Condominium association insurance: master property, D&O, fidelity bonds, and umbrella for condo boards. Bare-walls vs all-in explained, shopped across a variety of carriers.",
    title: "Condominium Association Insurance",
    hero: "condominium-association-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/homeowners-association-insurance/co-op-association-insurance",
    label: "Co-op Association",
    headline: "Co-op Association Insurance for Housing Cooperatives",
    support: "Co-op association insurance for housing cooperatives: blanket building property, board D&O, high-limit fidelity, and workers comp for staff. Shopped across a variety of carriers.",
    title: "Co-op Association Insurance",
    hero: "co-op-association-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/homeowners-association-insurance/hoa-board-insurance",
    label: "HOA Board",
    headline: "HOA Board Insurance That Protects Your Directors",
    support: "HOA board insurance is D&O that shields volunteer directors from personal exposure over rule enforcement, discrimination, and election disputes. Shopped across a variety of carriers.",
    title: "HOA Board Insurance",
    hero: "hoa-board-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/homeowners-association-insurance/planned-unit-development-insurance",
    label: "Planned Unit Development",
    headline: "Planned Unit Development Insurance for Your Association",
    support: "Planned unit development insurance mapped to lender PUD-project rules: common-element property, general liability, and D&O to keep PUD units warrantable.",
    title: "Planned Unit Development Insurance",
    hero: "planned-unit-development-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/homeowners-association-insurance/self-managed-hoa-insurance",
    label: "Self-Managed HOA",
    headline: "Self-Managed HOA Insurance for Boards Without a Manager",
    support: "Self-managed HOA insurance: master property, D&O, and fidelity bought direct, no management company. Coverage and renewals handled for volunteer boards.",
    title: "Self-Managed HOA Insurance",
    hero: "self-managed-hoa-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/homeowners-association-insurance/single-family-hoa-insurance",
    label: "Single-Family HOA",
    headline: "Single-Family HOA Insurance for Detached-Home Communities",
    support: "Single-family HOA insurance scoped to common areas and amenities: general liability, D&O, umbrella, and fidelity for detached-home associations. Shopped across a variety of carriers.",
    title: "Single-Family HOA Insurance",
    hero: "single-family-hoa-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/homeowners-association-insurance/townhome-association-insurance",
    label: "Townhome Association",
    headline: "Townhome Association Insurance for Attached Homes",
    support: "Townhome association insurance depends on whether you're recorded as a condominium or a PUD: master or common-area property, plus D&O, party-wall, and fidelity.",
    title: "Townhome Association Insurance",
    hero: "townhome-association-insurance-hero",
    categoryId: "home-owners-associations",
    parentPath: "/homeowners-association-insurance",
  },
  {
    path: "/property-management",
    label: "Property Management",
    headline: "Property management insurance that scales with your portfolio",
    support: "Insurance for property management companies: GL, E&O, fidelity bonds, cyber liability, and workers comp shopped across a variety of carriers. Free coverage review.",
    title: "Property Management Insurance",
    hero: "property-management-hero",
    categoryId: "property-management",
  },
  {
    path: "/property-management/commercial-property-management-insurance",
    label: "Commercial Property Management",
    headline: "Commercial property management insurance matched to your portfolio",
    support: "Insurance for commercial property management companies: GL, E&O, environmental liability, and umbrella shopped across a variety of carriers. Free coverage review.",
    title: "Commercial Property Management Insurance",
    hero: "commercial-property-management-insurance-hero",
    categoryId: "property-management",
    parentPath: "/property-management",
  },
  {
    path: "/property-management/multifamily-property-management-insurance",
    label: "Multifamily Property Management",
    headline: "Insurance for multifamily property management at scale",
    support: "Multifamily property management insurance: GL, E&O, workers comp, fidelity bonds, and EPLI for apartment managers. Shopped across a variety of carriers, flat fee.",
    title: "Multifamily Property Management Insurance",
    hero: "multifamily-property-management-insurance-hero",
    categoryId: "property-management",
    parentPath: "/property-management",
  },
  {
    path: "/property-management/residential-property-management-insurance",
    label: "Residential Property Management",
    headline: "Residential property management insurance for growing portfolios",
    support: "Residential property management insurance: GL, E&O, fidelity bonds, workers comp, and more. Shopped across a variety of carriers, flat fee. Free coverage review.",
    title: "Residential Property Management Insurance",
    hero: "residential-property-management-insurance-hero",
    categoryId: "property-management",
    parentPath: "/property-management",
  },
  {
    path: "/property-management/short-term-rental-management-insurance",
    label: "Short-Term Rental Management",
    headline: "Short-term rental management insurance that covers every booking",
    support: "Insurance for vacation rental managers and Airbnb co-hosts: GL, E&O, workers comp, innkeeper's liability, and cyber coverage shopped across a variety of carriers.",
    title: "Short-Term Rental Management Insurance",
    hero: "short-term-rental-management-insurance-hero",
    categoryId: "property-management",
    parentPath: "/property-management",
  },
  {
    path: "/restaurants",
    label: "Restaurant",
    headline: "Restaurant insurance shopped across a variety of carriers",
    support: "Restaurant insurance shopped across a variety of carriers for a flat fee. Liquor liability, premises, property, and workers' comp, with claims advocacy. Get a quote.",
    title: "Restaurant Insurance",
    hero: "restaurants-hero",
    categoryId: "restaurant",
  },
  {
    path: "/restaurants/fast-food-insurance",
    label: "Fast Food & QSR",
    headline: "Fast food insurance shopped across a variety of carriers",
    support: "Fast food insurance for QSR franchisees and multi-unit operators: drive-thru and delivery HNOA, fryer fire, EPLI, and franchisor-compliant certificates.",
    title: "Fast Food Insurance for QSR Franchisees",
    hero: "fast-food-insurance-hero",
    categoryId: "restaurant",
    parentPath: "/restaurants",
  },
  {
    path: "/restaurants/fine-dining-restaurant-insurance",
    label: "Fine Dining & Upscale",
    headline: "Fine dining insurance shopped across a variety of carriers",
    support: "Fine dining insurance for upscale restaurants: valet garagekeepers liability, a scheduled six-figure wine cellar, coat-check bailee coverage, and high liquor limits.",
    title: "Fine Dining Insurance for Upscale Restaurants",
    hero: "fine-dining-restaurant-insurance-hero",
    categoryId: "restaurant",
    parentPath: "/restaurants",
  },
  {
    path: "/restaurants/restaurant-group-insurance",
    label: "Restaurant Group & Multi-Unit",
    headline: "Restaurant group insurance shopped across a variety of carriers",
    support: "Restaurant group insurance on one master program: blanket limits, per-location certificates, multiple named insureds, and units added mid-term across the portfolio.",
    title: "Restaurant Group Insurance, Multi-Unit",
    hero: "restaurant-group-insurance-hero",
    categoryId: "restaurant",
    parentPath: "/restaurants",
  },
  {
    path: "/retail",
    label: "Retail Store",
    headline: "Retail store insurance built for brick-and-mortar operators",
    support: "Retail store insurance shopped across a variety of carriers for a flat fee. Slip-and-fall, property, theft, and business interruption, with claims advocacy. Get a quote.",
    title: "Retail Store Insurance Across a Variety of Carriers",
    hero: "retail-hero",
    categoryId: "retail-store",
  },
  {
    path: "/technology",
    label: "Technology",
    headline: "Technology insurance that keeps up with how fast you ship",
    support: "Technology insurance for SaaS, IT, fintech, and startups. We shop a variety of carriers for Tech E&O, cyber, and D&O coverage, including E&S markets for AI and crypto. Free coverage review, no obligation.",
    title: "Technology Company Insurance",
    hero: "technology-hero",
    categoryId: "technology",
  },
  {
    path: "/technology/crypto-company-insurance",
    label: "Crypto & Web3 Company",
    headline: "Crypto company insurance engineered for digital-asset risk",
    support: "Crypto company insurance for exchanges, custodians, token issuers, and Web3 protocols: digital-asset crime, D&O, cyber, specie, and Tech E&O.",
    title: "Crypto Company Insurance",
    hero: "crypto-company-insurance-hero",
    categoryId: "technology",
    parentPath: "/technology",
  },
  {
    path: "/technology/cybersecurity-company-insurance",
    label: "Cybersecurity Company",
    headline: "Cybersecurity company insurance placed when standard markets decline",
    support: "MSSP and cybersecurity company insurance for penetration testers, SOC providers, and security software: failure-to-perform Tech E&O, cyber, and D&O.",
    title: "MSSP & Cybersecurity Company Insurance",
    hero: "cybersecurity-company-insurance-hero",
    categoryId: "technology",
    parentPath: "/technology",
  },
  {
    path: "/technology/fintech-insurance",
    label: "Fintech",
    headline: "Fintech insurance structured for regulated financial risk",
    support: "Insurance for fintech companies handling payments, lending, and financial data: financial-services E&O, cyber, D&O, and commercial crime.",
    title: "Fintech Insurance for Payments & Lending",
    hero: "fintech-insurance-hero",
    categoryId: "technology",
    parentPath: "/technology",
  },
  {
    path: "/technology/saas-insurance",
    label: "SaaS",
    headline: "SaaS insurance scoped for how you sell software",
    support: "Insurance for SaaS companies: Tech E&O, SaaS cyber insurance, D&O, and contract-required endorsements shopped across a variety of carriers.",
    title: "SaaS Insurance for B2B Software Companies",
    hero: "saas-insurance-hero",
    categoryId: "technology",
    parentPath: "/technology",
  },
  {
    path: "/trucking",
    label: "Trucking",
    headline: "Trucking insurance that works as hard as your fleet",
    support: "Trucking insurance shopped across a variety of carriers for owner-operators and fleets. Flat-fee brokerage, a response within the next hour. Free coverage review.",
    title: "Trucking Insurance",
    hero: "trucking-hero",
    categoryId: "trucking",
  },
  {
    path: "/trucking/box-truck-insurance",
    label: "Box Truck",
    headline: "Box truck insurance built for last-mile fleets",
    support: "Box truck insurance for local delivery, moving, and last-mile operations. Commercial auto, cargo, and physical damage quoted across a variety of carriers. Free review.",
    title: "Box Truck Insurance",
    hero: "box-truck-insurance-hero",
    categoryId: "trucking",
    parentPath: "/trucking",
  },
  {
    path: "/trucking/dump-truck-insurance",
    label: "Dump Truck",
    headline: "Dump truck insurance rated for construction haulers",
    support: "Dump truck insurance for construction haulers. Commercial auto, GL with completed operations, pollution liability. Quoted across a variety of carriers.",
    title: "Dump Truck Insurance",
    hero: "dump-truck-insurance-hero",
    categoryId: "trucking",
    parentPath: "/trucking",
  },
  {
    path: "/trucking/semi-truck-insurance",
    label: "Semi Truck",
    headline: "Semi truck insurance structured for owner-operators and fleets",
    support: "Semi truck insurance for owner-operators and small fleets. FMCSA-compliant liability, physical damage, and cargo coverage quoted across a variety of carriers.",
    title: "Semi Truck Insurance",
    hero: "semi-truck-insurance-hero",
    categoryId: "trucking",
    parentPath: "/trucking",
  },
  {
    path: "/trucking/tow-truck-insurance",
    label: "Tow Truck",
    headline: "Tow truck insurance engineered for recovery operations",
    support: "Tow truck insurance for towing companies and roadside operators. On-hook, garagekeepers, commercial auto, and full programs quoted across a variety of carriers.",
    title: "Tow Truck Insurance",
    hero: "tow-truck-insurance-hero",
    categoryId: "trucking",
    parentPath: "/trucking",
  },
];

export const INDUSTRY_HUB_PATHS = [
  "/financial-products",
  "/ecommerce",
  "/homeowners-association-insurance",
  "/property-management",
  "/restaurants",
  "/grocery-stores",
  "/trucking",
  "/garages",
  "/contractors",
  "/technology",
  "/retail",
  "/bar-insurance",
  "/catering-insurance",
] as const;

const byPath = new Map(INDUSTRY_PAGES.map((p) => [p.path, p]));

export function getIndustryPage(path: string): IndustryPage | undefined {
  const clean = path.endsWith("/") && path !== "/" ? path.slice(0, -1) : path;
  return byPath.get(clean.startsWith("/") ? clean : `/${clean}`);
}

export function getIndustryChildren(parentPath: string): IndustryPage[] {
  const clean = parentPath.endsWith("/") && parentPath !== "/" ? parentPath.slice(0, -1) : parentPath;
  return INDUSTRY_PAGES.filter((p) => p.parentPath === clean);
}

export function industryHref(path: string): string {
  const clean = path.endsWith("/") && path !== "/" ? path.slice(0, -1) : path;
  return `${clean.startsWith("/") ? clean : `/${clean}`}/`;
}

/** Nested slug segments under a category hub (without leading path). */
export function industryChildSlugs(hubPath: string): string[] {
  return getIndustryChildren(hubPath).map((p) => p.path.split("/").pop()!);
}

/**
 * All single-segment slugs under a hub, including pages whose parent is an
 * intermediate hub (e.g. term leaves under /life-insurance/term-insurance).
 */
export function industrySegmentSlugs(hubPath: string): string[] {
  const clean =
    hubPath.endsWith("/") && hubPath !== "/" ? hubPath.slice(0, -1) : hubPath;
  return INDUSTRY_PAGES.filter((p) => {
    if (!p.path.startsWith(`${clean}/`)) return false;
    const rest = p.path.slice(clean.length + 1);
    return rest.length > 0 && !rest.includes("/");
  }).map((p) => p.path.split("/").pop()!);
}
